In [ ]:
import pandas as pd

In [ ]:
train_data = pd.read_csv("fraudTrain.csv")

In [ ]:
train_data.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495.0,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149.0,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154.0,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939.0,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99.0,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0

In [ ]:
train_data.shape

(128241, 23)

In [ ]:
train_data.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [ ]:
train_data['is_fraud'].value_counts()

is_fraud
0.0    127059
1.0      1181
Name: count, dtype: int64

In [ ]:
train_data[['amt','is_fraud']].head()

NameError: name 'train_data' is not defined

In [ ]:
import pandas as pd

In [ ]:
train_data = pd.read_csv("fraudTrain.csv")

In [ ]:
train_data[['amt','is_fraud']].head()

NameError: name 'train_data' is not defined

In [ ]:
train_data[['amt','is_fraud']].head()

NameError: name 'train_data' is not defined

In [ ]:
import pandas as pd

In [ ]:
train_data = pd.read_csv("fraudTrain.csv")

In [ ]:
train_data[['amt','is_fraud']].head()

      amt  is_fraud
0    4.97       0.0
1  107.23       0.0
2  220.11       0.0
3   45.00       0.0
4   41.96       0.0

In [ ]:
X = train_data[['amt']]
y = train_data['is_fraud']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(21807, 1)
(5452, 1)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
X =  train_data[['amt']]
y = train_data['is_fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print("Model Trained Successfully")

NameError: name 'train_data' is not defined

In [ ]:
import pandas as pd
train_data = pd.read_csv("fraudTrain.csv")
print(train_data.shape)

(108881, 23)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
X =  train_data[['amt']]
y = train_data['is_fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print("Model Trained Successfully")

ValueError: Input y contains NaN.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
X =  train_data[['amt']].fillna(0)
y = train_data['is_fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print("Model Trained Successfully")

ValueError: Input y contains NaN.

In [ ]:
train_data['is_fraud'].isnull().sum()

np.int64(1)

In [ ]:
train_data = train_data.dropna(subset=['is_fraud'])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
X =  train_data[['amt']].fillna(0)
y = train_data['is_fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print("Model Trained Successfully")

Model Trained Successfully

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Fraud Detection Accuracy:", accuracy * 100, "%")

Fraud Detection Accuracy: 98.95756796473182 %